on: [push]
name: Docker Push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build & Push to GitHub Package
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.GITHUB_USERNAME }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: "docker.pkg.github.com"
          TAG_NAME: ${{ github.sha }}
          LATEST: "true"

      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "${{ github.repository }}"
          TAG_NAME: ${{ github.sha }}
          LATEST: "true"
